/*globals define, _, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Fri Jul 21 2023 22:01:49 GMT-0500 (Central Daylight Time).
 */
define([
    'js/PanelBase/PanelBaseWithHeader',
    'js/PanelManager/IActivePanel',
    'Othello_Game_Design_Studio/bundles/OthelloWidget.bundle', // Renamed ReactToeWidget to OthelloWidget
    './OthelloControl' // Renamed ReactToeControl to OthelloControl
], function (
    PanelBaseWithHeader,
    IActivePanel,
    OthelloWidget, // Renamed ReactToeWidget to OthelloWidget
    OthelloControl // Renamed ReactToeControl to OthelloControl
) {
    'use strict';

    function OthelloVizPanel(layoutManager, params) {
        var options = {};
        //set properties from options
        options[PanelBaseWithHeader.OPTIONS.LOGGER_INSTANCE_NAME] = 'OthelloVizPanel';
        options[PanelBaseWithHeader.OPTIONS.FLOATING_TITLE] = true;

        //call parent's constructor
        PanelBaseWithHeader.apply(this, [options, layoutManager]);

        this._client = params.client;
        this.appId = `Othello-viz-id`; // Changed appId to Othello

        //initialize UI
        this._initialize();

        this.logger.debug('ctor finished');
    }

    //inherit from PanelBaseWithHeader
    _.extend(OthelloVizPanel.prototype, PanelBaseWithHeader.prototype);
    _.extend(OthelloVizPanel.prototype, IActivePanel.prototype);

    OthelloVizPanel.prototype._initialize = function () {

        this.$el.prop('id', this.appId);
        this.$el.css({
            width: '100%',
            height: '100%',
        });

        this.control = new OthelloControl({ // Using OthelloControl
            logger: this.logger,
            client: this._client
        });

        this.widget = null;

        this.onActivate();
    };

    OthelloVizPanel.prototype.afterAppend = function afterAppend() {
        console.log('AFTER APPEND');
        OthelloWidget(this.appId, this.control, this); // Using OthelloWidget
    };

    /* OVERRIDE FROM WIDGET-WITH-HEADER */
    /* METHOD CALLED WHEN THE WIDGET'S READ-ONLY PROPERTY CHANGES */
    OthelloVizPanel.prototype.onReadOnlyChanged = function (isReadOnly) {
        //apply parent's onReadOnlyChanged
        PanelBaseWithHeader.prototype.onReadOnlyChanged.call(this, isReadOnly);
    };

    /*OthelloVizPanel.prototype.onResize = function (width, height) {
        this.logger.debug('onResize --> width: ' + width + ', height: ' + height);
        this.widget.onWidgetContainerResize(width, height);
    };*/

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    OthelloVizPanel.prototype.destroy = function () {
        this.control.destroy();
        // this.widget.destroy();

        PanelBaseWithHeader.prototype.destroy.call(this);
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    OthelloVizPanel.prototype.onActivate = function () {
        this.control.onActivate();
        WebGMEGlobal.KeyboardManager.setListener(this.widget);
        WebGMEGlobal.Toolbar.refresh();
    };

    OthelloVizPanel.prototype.onDeactivate = function () {
        this.control.onDeactivate();
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    return OthelloVizPanel;
});
