/*globals define, _, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Sun Dec 10 2023 14:11:17 GMT-0600 (Central Standard Time).
 */

define([
    'js/PanelBase/PanelBaseWithHeader',
    'js/PanelManager/IActivePanel',
    'widgets/ReactToe/ReactToeWidget',
    './ReactToeControl'
], function (
    PanelBaseWithHeader,
    IActivePanel,
    ReactToeWidget,
    ReactToeControl
) {
    'use strict';

    function ReactToePanel(layoutManager, params) {
        var options = {};
        //set properties from options
        options[PanelBaseWithHeader.OPTIONS.LOGGER_INSTANCE_NAME] = 'ReactToePanel';
        options[PanelBaseWithHeader.OPTIONS.FLOATING_TITLE] = true;

        //call parent's constructor
        PanelBaseWithHeader.apply(this, [options, layoutManager]);

        this._client = params.client;
        this.appId = `ReactToe-viz-id`;
        //initialize UI
        this._initialize();

        this.logger.debug('ctor finished');
    }

    //inherit from PanelBaseWithHeader
    _.extend(ReactToePanel.prototype, PanelBaseWithHeader.prototype);
    _.extend(ReactToePanel.prototype, IActivePanel.prototype);

    ReactToePanel.prototype._initialize = function () {
        var self = this;

        //set Widget title
        this.setTitle('');

        this.widget = new ReactToeWidget(this.logger, this.$el);

        this.widget.setTitle = function (title) {
            self.setTitle(title);
        };

        this.control = new ReactToeControl({
            logger: this.logger,
            client: this._client,
            widget: this.widget
        });

        this.onActivate();
    };

    ReactToePanel.prototype.afterAppend = function afterAppend() {
        console.log('AFTER APPEND');
        /*if(!this.widget) {
            this.widget = ReactToeWidget(this.appId, this.control, this);
        }*/
        ReactToeWidget(this.appId, this.control, this);
    };

    /* OVERRIDE FROM WIDGET-WITH-HEADER */
    /* METHOD CALLED WHEN THE WIDGET'S READ-ONLY PROPERTY CHANGES */
    ReactToePanel.prototype.onReadOnlyChanged = function (isReadOnly) {
        //apply parent's onReadOnlyChanged
        PanelBaseWithHeader.prototype.onReadOnlyChanged.call(this, isReadOnly);

    };
    // ReactToePanel.prototype.onResize = function (width, height) {
    //     this.logger.debug('onResize --> width: ' + width + ', height: ' + height);
    //     this.widget.onWidgetContainerResize(width, height);
    // };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    ReactToePanel.prototype.destroy = function () {
        this.control.destroy();
        this.widget.destroy();

        PanelBaseWithHeader.prototype.destroy.call(this);
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    ReactToePanel.prototype.onActivate = function () {
        this.widget.onActivate();
        this.control.onActivate();
        WebGMEGlobal.KeyboardManager.setListener(this.widget);
        WebGMEGlobal.Toolbar.refresh();
    };

    ReactToePanel.prototype.onDeactivate = function () {
        this.widget.onDeactivate();
        this.control.onDeactivate();
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    return ReactToePanel;
});
